
apiVersion: v1
kind: Pod
metadata:
  name: test-pod123
spec:
  containers:
  - name: test-container
    image: nginx:latest
    ports:
    - containerPort: 80
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Equal"
    value: ""
    effect: "NoSchedule"
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""